/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.opennms.integration.tmf621.camel.api;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;
import org.apache.camel.LoggingLevel;
import org.opennms.integration.tmf621.camel.model.*;
import org.apache.camel.model.dataformat.JsonLibrary;

@Component
public class HubApiRoutesImpl extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        
        /**
        POST /hub : Register a listener
        **/
        from("direct:registerListener")
            .id("registerListener")
            .choice()
                .when(simple("${body} != null"))
                    .log(LoggingLevel.INFO, "BODY TYPE: ${body.getClass().getName()}")
            .end()
            .log(LoggingLevel.INFO, "HEADERS: ${headers}")
            .setBody(constant("{ \"query\" : \"query\", \"callback\" : \"callback\", \"id\" : \"id\" }"))
            .unmarshal().json(JsonLibrary.Jackson, EventSubscription.class);
        /**
        DELETE /hub/{id} : Unregister a listener
        **/
        from("direct:unregisterListener")
            .id("unregisterListener")
            .choice()
                .when(simple("${body} != null"))
                    .log(LoggingLevel.INFO, "BODY TYPE: ${body.getClass().getName()}")
            .end()
            .log(LoggingLevel.INFO, "HEADERS: ${headers}");
    }
}
