/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.opennms.integration.tmf621.camel.api;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;
import org.apache.camel.LoggingLevel;

@Component
public class HubApiValidator extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        onException(Exception.class)
            .log(LoggingLevel.ERROR, "${exception.message}: ${exception.stacktrace}")
            .handled(true)
            .process("validationErrorProcessor");
        
        from("direct:validate-registerListener")
            .id("validate-registerListener")
            .to("bean-validator://validate-request")
            .to("direct:registerListener")
            .to("bean-validator://validate-response");
        
        from("direct:validate-unregisterListener")
            .id("validate-unregisterListener")
            .to("direct:unregisterListener")
            .to("bean-validator://validate-response");
        
    }
}
