/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.opennms.integration.tmf621.camel.api;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.stereotype.Component;
import org.opennms.integration.tmf621.camel.model.*;
import org.apache.camel.model.rest.RestBindingMode;
import org.apache.camel.LoggingLevel;

@Component
public class ListenerApi extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        onException(Exception.class)
            .log(LoggingLevel.ERROR, "${exception.message}: ${exception.stacktrace}")
            .handled(true)
            .process("validationErrorProcessor");
        

        /**
        POST /listener/troubleTicketAttributeValueChangeEvent : Client listener for entity TroubleTicketAttributeValueChangeEvent
        **/
        rest()
            .post("/listener/troubleTicketAttributeValueChangeEvent")
                .description("Client listener for entity TroubleTicketAttributeValueChangeEvent")
                .id("listenToTroubleTicketAttributeValueChangeEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketAttributeValueChangeEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketAttributeValueChangeEvent");
        

        /**
        POST /listener/troubleTicketCreateEvent : Client listener for entity TroubleTicketCreateEvent
        **/
        rest()
            .post("/listener/troubleTicketCreateEvent")
                .description("Client listener for entity TroubleTicketCreateEvent")
                .id("listenToTroubleTicketCreateEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketCreateEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketCreateEvent");
        

        /**
        POST /listener/troubleTicketDeleteEvent : Client listener for entity TroubleTicketDeleteEvent
        **/
        rest()
            .post("/listener/troubleTicketDeleteEvent")
                .description("Client listener for entity TroubleTicketDeleteEvent")
                .id("listenToTroubleTicketDeleteEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketDeleteEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketDeleteEvent");
        

        /**
        POST /listener/troubleTicketInformationRequiredEvent : Client listener for entity TroubleTicketInformationRequiredEvent
        **/
        rest()
            .post("/listener/troubleTicketInformationRequiredEvent")
                .description("Client listener for entity TroubleTicketInformationRequiredEvent")
                .id("listenToTroubleTicketInformationRequiredEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketInformationRequiredEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketInformationRequiredEvent");
        

        /**
        POST /listener/troubleTicketResolvedEvent : Client listener for entity TroubleTicketResolvedEvent
        **/
        rest()
            .post("/listener/troubleTicketResolvedEvent")
                .description("Client listener for entity TroubleTicketResolvedEvent")
                .id("listenToTroubleTicketResolvedEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketResolvedEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketResolvedEvent");
        

        /**
        POST /listener/troubleTicketStatusChangeEvent : Client listener for entity TroubleTicketStatusChangeEvent
        **/
        rest()
            .post("/listener/troubleTicketStatusChangeEvent")
                .description("Client listener for entity TroubleTicketStatusChangeEvent")
                .id("listenToTroubleTicketStatusChangeEventApi")
                .clientRequestValidation(false)
                .bindingMode(RestBindingMode.off)
                .produces("application/json;charset=utf-8")
                .outType(EventSubscription.class)
                .consumes("application/json;charset=utf-8")
                .type(TroubleTicketStatusChangeEvent.class)
                
                .param()
                    .name("data")
                    .type(RestParamType.body)
                    .required(true)
                    .description("The event data")
                .endParam()
                .to("direct:validate-listenToTroubleTicketStatusChangeEvent");
        
    }
}
