/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.opennms.integration.tmf621.camel.api;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;
import org.apache.camel.LoggingLevel;

@Component
public class TroubleTicketApiValidator extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        onException(Exception.class)
            .log(LoggingLevel.ERROR, "${exception.message}: ${exception.stacktrace}")
            .handled(true)
            .process("validationErrorProcessor");
        
        from("direct:validate-createTroubleTicket")
            .id("validate-createTroubleTicket")
            .to("bean-validator://validate-request")
            .to("direct:createTroubleTicket")
            .to("bean-validator://validate-response");
        
        from("direct:validate-deleteTroubleTicket")
            .id("validate-deleteTroubleTicket")
            .to("direct:deleteTroubleTicket")
            .to("bean-validator://validate-response");
        
        from("direct:validate-listTroubleTicket")
            .id("validate-listTroubleTicket")
            .to("direct:listTroubleTicket")
            .to("bean-validator://validate-response");
        
        from("direct:validate-patchTroubleTicket")
            .id("validate-patchTroubleTicket")
            .to("bean-validator://validate-request")
            .to("direct:patchTroubleTicket")
            .to("bean-validator://validate-response");
        
        from("direct:validate-retrieveTroubleTicket")
            .id("validate-retrieveTroubleTicket")
            .to("direct:retrieveTroubleTicket")
            .to("bean-validator://validate-response");
        
    }
}
